version: "3.8"

services:
  backend:
    build:
      context: ./email-writer-sp
    container_name: email-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=AIzaSyDkQingIowZJHEj8XyZEpG5dxH3Bk1ejLI
      - GEMINI_API_URL=/v1beta/models/gemini-2.0-flash:generateContent
    restart: unless-stopped

  frontend:
    build:
      context: ./email-writer-frontend
    container_name: email-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

