version: "3.8"

services:
  backend:
    build:
      context: ./email-writer-sp
    container_name: email-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./email-writer-frontend
    container_name: email-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

